version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
  build:
    commands:
      - serverless package --stage devel --package ./artifacts
  post_build:
    commands:
      - echo build complete
artifacts:
  files:
    - '**/*'

