version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless@1.4.0
  build:
    commands:
      - serverless package --stage devel --package ./artifacts
  post_build:
    commands:
      - echo build complete
artifacts:
  files:
    - '**/*'
      
