version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless
  build:
    commands:
      - ls ./artifacts
      - cat ./artifacts/serverless-state.json
      - serverless deploy --stage devel --package ./artifacts
  post_build:
    commands:
      - echo build complete
      
